// Library entry: trading tools, exchange layer and runtime for programmatic use.

export type {
	Balance,
	ContractStats,
	ContractType,
	ExchangeClient,
	FundingRateRecord,
	Kline,
	MarketDataClient,
	MarketInfo,
	Order,
	OrderBook,
	OrderBookLevel,
	OrderList,
	OrderSide,
	OrderStatus,
	OrderType,
	PlaceOcoOrderInput,
	PlaceOcoOrderResult,
	PlaceOrderInput,
	PlaceOrderResult,
	PlaceOrderType,
	Position,
	Ticker,
} from "@nikopack/ti-trading-engine";
export { createTradingExtension } from "./commands.ts";
export {
	AGENT_DIR,
	APP_NAME,
	CONFIG_DIR,
	CONFIG_DIR_NAME,
	KEYS_PATH,
	PAPER_DIR,
	TRADING_CONFIG_PATH,
} from "./config.ts";
export {
	AccountSwitchConfirmationRequired,
	type AccountSwitchOptions,
	getTrading,
	initTrading,
	TradingRuntime,
} from "./context.ts";
export { createOperationalHealthExtension, readOperationalHealth } from "./health.ts";
export { main } from "./main.ts";
export {
	assessOperationalHealth,
	type OperationalHealthInput,
	type OperationalObservation,
} from "./operational-health.ts";
export { buildTradingPrompt } from "./prompt.ts";
export {
	DEFAULT_CONFIG,
	type ExchangeCredentials,
	type FuturesMarginType,
	type FuturesPositionMode,
	loadExchangeKeys,
	loadTradingConfig,
	type MarketType,
	type RiskLimits,
	saveExchangeKeys,
	saveTradingConfig,
	type TradingConfig,
	type TradingMode,
} from "./state.ts";
export {
	createBuyTool,
	createCancelOrderListTool,
	createCancelOrderTool,
	createCheckOrderTool,
	createGetBalanceTool,
	createGetContractStatsTool,
	createGetFundingRateHistoryTool,
	createGetFundingRateTool,
	createGetFuturesPositionsTool,
	createGetKlinesTool,
	createGetMarketInfoTool,
	createGetOpenOrdersTool,
	createGetOrderBookTool,
	createGetOrderHistoryTool,
	createGetOrderListStatusTool,
	createGetOrderStatusTool,
	createGetPortfolioSnapshotTool,
	createGetPositionsTool,
	createGetPriceTool,
	createGetRiskStatusTool,
	createGetTopMarketsTool,
	createGetTradingCapabilitiesTool,
	createPlaceOcoTool,
	createSellTool,
	createSetLeverageTool,
	createSetMarginModeTool,
	createSetMultiAssetsModeTool,
	createTradingTools,
	type TradingProvider,
} from "./tools/index.ts";
